version: '3'
services:

  eureka-serviceregistry:
    build:
      context: ./MainApp/Servers/eureka
    container_name: eureka-serviceregistry
    ports:
      - "8761:8761"
    tty: true

  postgres:
    image: 'postgres'
    container_name: postgres
    restart: always
    environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=test_database
        - REGISTRY_HOST=eureka-serviceregistry
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    tty: true
  
  axon-server:
    image: axoniq/axonserver:4.3.2
    ports:
      - 8024:8024
      - 8124:8124

  user:
    build:
      context: ./MainApp/Servers/user
      dockerfile: Dockerfile.prod
    ports:
    - "8081:8081"
    tty: true
    environment:
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
      DATABASE_DOMAIN: postgres
      REGISTRY_HOST: eureka-serviceregistry
      POSTGRES_DB: test_database
    depends_on:
      - eureka-serviceregistry
      - postgres
      - axon-server
    volumes:
      - $USERPROFILE/.m2:/root/.m2

  rental:
    build:
      context: ./MainApp/Servers/rental
      dockerfile: Dockerfile.prod
    ports:
    - "8082:8080"
    environment:
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
      DATABASE_DOMAIN: postgres
      REGISTRY_HOST: eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - postgres
      - axon-server
    volumes: 
      - $USERPROFILE/.m2:/root/.m2

  search:
    build:
      context: ./MainApp/Servers/search
      dockerfile: Dockerfile.prod
    ports:
    - "8083:8080"
    environment:
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
      DATABASE_DOMAIN: postgres
      REGISTRY_HOST: eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - postgres
      - axon-server
    volumes: 
      - $USERPROFILE/.m2:/root/.m2

  vehicle:
    build:
      context: ./MainApp/Servers/vehicle
      dockerfile: Dockerfile.prod
    ports:
    - "8084:8080"
    environment:
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
      DATABASE_DOMAIN: postgres
      REGISTRY_HOST: eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - postgres
      - axon-server
    volumes: 
      - $USERPROFILE/.m2:/root/.m2

  location:
    build:
      context: ./MainApp/Servers/location
      dockerfile: Dockerfile.prod
    ports:
    - "8085:8080"
    environment:
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
      DATABASE_DOMAIN: postgres
      REGISTRY_HOST: eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - postgres
      - axon-server
    volumes: 
      - $USERPROFILE/.m2:/root/.m2

  chat:
    build:
      context: ./MainApp/Servers/chat
      dockerfile: Dockerfile.prod
    ports:
    - "8086:8080"
    environment:
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
      DATABASE_DOMAIN: postgres
      REGISTRY_HOST: eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - postgres
      - axon-server
    volumes: 
      - $USERPROFILE/.m2:/root/.m2

  # front:
  #   build: ./MainApp/Client
  #   ports:
  #   - "4200:4200"
  #   environment:
  #     - REGISTRY_HOST=eureka-serviceregistry
  #   tty: true
  #   volumes:
  #     - ./MainApp/Client:/usr/src/Client
  #     - /usr/src/Client/node_modules

  zuul:
    build:
      context: ./MainApp/Servers/zuul
      dockerfile: Dockerfile.prod
    ports:
    - "8087:8083"
    environment:
      DATABASE_USERNAME: test
      DATABASE_PASSWORD: test
      DATABASE_DOMAIN: postgres
      REGISTRY_HOST: eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - postgres
      - axon-server
      - user
    volumes:
      - $USERPROFILE/.m2:/root/.m2

volumes:
  database-data:
  front-storage:
  maven-repo:
  maven-repo2:
