version: '3'
services:

  eureka-serviceregistry:
    build: ./MainApp/Servers/eureka
    networks:
      - demo
    ports:
      - "8761:8761"
    tty: true

  postgres:
    image: 'postgres'
    container_name: postgres
    restart: always
    networks:
      - demo
    environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=test
        - POSTGRES_PASSWORD=test
        - POSTGRES_DB=test_database
        - REGISTRY_HOST=eureka-serviceregistry
    ports:
      - 5432:5432
    tty: true
  
  axon-server:
    image: axoniq/axonserver:4.3.2
    networks:
      - demo
    ports:
      - 8024:8024
      - 8124:8124

  xmlws:
    build: ./MainApp/Servers/xmlws
    ports:
    - "8081:8080"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - postgres
      - axon-server

  front:
    build: ./MainApp/Client
    ports:
    - "4200:4200"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
      #- CHOKIDAR_USEPOLLING=true
    tty: true
    volumes:
      - ./MainApp/Client:/usr/src/Client      #  - /XML_WS/MainApp/Client:/usr/src/Client  
      - /usr/src/Client/node_modules          #  - /XML_WS/MainApp/Client/node_modules

  zuul:
    build: ./MainApp/Servers/zuul
    networks:
      - demo
    ports:
    - "8083:8083"
    environment:
      - REGISTRY_HOST=eureka-serviceregistry
    tty: true
    depends_on:
      - eureka-serviceregistry
      - postgres
      - axon-server
      - xmlws

networks:
  demo:
    driver: bridge

volumes:
  database-data:
  front-storage:
