zuul:
  routes:
    # ----- USER -----
    user:
      path: /test/**
      stripPrefix: false
      serviceId: user
    user1:
      path: /auth/**
      stripPrefix: false
      serviceId: user
    user2:
      path: /user/**
      stripPrefix: false
      serviceId: user

    # ----- RENTAL -----
    rental:
      path: /rental/**
      stripPrefix: false
      serviceId: rental
    rental1:
      path: /bundle/**
      stripPrefix: false
      serviceId: rental
    rental2:
      path: /customer/**/rental
      stripPrefix: false
      serviceId: rental
    rental3:
      path: /vehicle/**/rental
      stripPrefix: false
      serviceId: rental
    rental4:
      path: /owner/**/rental
      stripPrefix: false
      serviceId: rental

    zuul: # needed for the auth filter to work
      path: /checkout
      stripPrefix: false
      url: forward:/
