zuul:
  routes:
    # ----- USER -----
    user:
      path: /test/**
      stripPrefix: false
      serviceId: user
    user1:
      path: /auth/**
      stripPrefix: false
      serviceId: user
    user2:
      path: /user/**
      stripPrefix: false
      serviceId: user

    # ----- RENTAL -----
    rental:
      path: /rental/**
      stripPrefix: false
      serviceId: rental
    rental1:
      path: /bundle/**
      stripPrefix: false
      serviceId: rental
    rental2:
      path: /customer/**/rental
      stripPrefix: false
      serviceId: rental
    rental3:
      path: /vehicle/**/rental
      stripPrefix: false
      serviceId: rental
    rental4:
      path: /owner/**/rental
      stripPrefix: false
      serviceId: rental

    # ----- VEHICLE -----
    vehicle:
      path: /brand/**
      stripPrefix: false
      serviceId: vehicle
    vehicle1:
      path: /category/**
      stripPrefix: false
      serviceId: vehicle
    vehicle2:
      path: /transmission/**
      stripPrefix: false
      serviceId: vehicle
    vehicle3:
      path: /fuel/**
      stripPrefix: false
      serviceId: vehicle
    vehicle4:
      path: /vehicle/**
      stripPrefix: false
      serviceId: vehicle
    vehicle5:
      path: /pricelist/**
      stripPrefix: false
      serviceId: vehicle
    vehicle6:
      path: /review/**
      stripPrefix: false
      serviceId: vehicle
    vehicle7:
      path: /owner/{id}/vehicle
      stripPrefix: false
      serviceId: vehicle

    # ----- SEARCH -----
    search:
      path: /search/**
      stripPrefix: false
      serviceId: search


    zuul: # needed for the auth filter to work
      path: /checkout
      stripPrefix: false
      url: forward:/
